### ISSUE TITLE
Add deployment workflow

### ISSUE THREAD

**Issue by kwunyeung** [forbole/landing-page-v2#102]
I have created this workflow which I successfully deploy the BD for Flow Nextjs app to the server every time I merge a PR to master.

https://github.com/forbole/big-dipper-flow-client/blob/master/.github/workflows/node.js.yml

I store the content of the whole `.env` in the Github Secret and create the file every time right before build.

**Comment by kwunyeung** [comment]
@ryuash @rachelhox I prefer we create a Github action on the website so that every time we merge the PR to master branch will trigger a deployment on the web server. In this workflow, no matter we are updating the graphics or text on the Nextjs app, the new changes will be applied and we don't have to build the app manually.

The marcom team can also just learn how to edit text files on Github directly and create a PR. After we have reviewed the code and merge, the new changes will be deployed. This is loose the uncertainty from the marcom team when they would like to make changes on the content but not the features of the website.

**Comment by ryuash** [comment]
Will probably set this up next week
