### ISSUE TITLE
Animation with React

### ISSUE THREAD

**Issue by kwunyeung** [forbole/landing-page-v2#77]
If found directly controlling `CSS` animation is difficult, there are different animation libraries work with `React`.

1. [Framer Motion (formerly Pose)](https://github.com/framer/motion)

I think **Framer** acquired them and applied it on Framer.

2. [Velocity React](https://github.com/google-fabric/velocity-react)

A library that make React component work with `Velocity.js`. I think `Velocity.js` is the most comprehensive animation library in `JavaScript` now.

The benefit of making use of the libraries is that they provide the tweening timing and easing functions so that you don't have to calculate the changes on every step.

**Comment by ryuash** [comment]
@kwunyeung We're currently using react spring but I decided to opt out and use raw css as it was easier to control in this use case. The animation issue is actually fixed in the current master and should be closer to the wireframe.
