### ISSUE TITLE
Filenaming standard

### ISSUE THREAD

**Issue by kwunyeung** [forbole/landing-page-v2#78]
I would prefer naming the files with **hyphen** rather than **underscore**. Although both of them are valid file names, using hyphens will reduce the chances of making mistakes as you don't type `SHIFT` with the character. And for public files like those image files can be accessible by public, they should be in `-` as search engines see `-` as a word separator which `forbole-logo.svg` will be read as `forbole logo` and `_` is for word concatenation, so `forbole_logo.svg` will be read as `forbolelogo`.

**Comment by ryuash** [comment]
@kwunyeung hmm I will open an issue for the files inside public to be hyphen for SEO purposes but I think it's best to hold off on renaming all the files in src. There is not much advantage to changing all of them at the moment as they won't affect the SEO like the files inside public

**Comment by kwunyeung** [comment]
@ryuash agree. Only public files have to be catered at this stage.
