### ISSUE TITLE
Detecting background dark or light

### ISSUE THREAD

**Issue by kwunyeung** [forbole/landing-page-v2#79]
This is a detect script we had used before

https://www.kennethcachia.com/background-check/

We applied to Creativeworks website so that when a user scroll the page, the colour of the logo will switch.

https://www.creativeworks.com.hk/works

**Comment by ryuash** [comment]
@kwunyeung  Spoke to the designer on Tuesday. The current master should fix the navbar issue as only one page needs to be specially handled.
