### ISSUE TITLE
update about page with real data

### ISSUE THREAD

**Issue by ryuash** [forbole/landing-page-v2#99]

**Comment by kwunyeung** [comment]
Chains to be integrated

Total staking value
https://staging.forbole.com/stake-now

1. Cosmos Hub
2. Solana
2. IRISnet
3. Terra 
4. Kava
5. Akash
6. Band
7. Kusama
8. Polkadot
9. IOV
10. Likecoin
11. Oasis
12. Vsys
13. IPX
12. Aion

Updated prices can be retrieved from [Coingecko API](https://www.coingecko.com/api/documentations/v3).
